### ISSUE TITLE
Edit action doesn't work

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#158]
Tried to run `/timereport edit sjuk 2020-01-10` and got no response from slack.

Saw this in the logs:
```
[DEBUG]	2020-01-13T19:53:42.760Z	7e999ae1-5004-4a98-baf7-ec3f43323d28	Action is: edit

[DEBUG]	2020-01-13T19:53:42.760Z	7e999ae1-5004-4a98-baf7-ec3f43323d28	Arguments are: ['sjuk', '2020-01-10']

[DEBUG]	2020-01-13T19:53:42.760Z	7e999ae1-5004-4a98-baf7-ec3f43323d28	Got 2 number of args

[CRITICAL]	2020-01-13T19:53:42.760Z	7e999ae1-5004-4a98-baf7-ec3f43323d28	Caught unhandled exception.
Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    action.perform_action()
  File "/var/task/chalicelib/action.py", line 60, in perform_action
    return self._edit_action()
  File "/var/task/chalicelib/action.py", line 215, in _edit_action
    hours = round(float(self.arguments[2]))
IndexError: list index out of range
```
We have a try/catch, but it doesn't catch `IndexError`, which it should because the hours should be optional.

**Comment by parberge** [comment]
Right this is because we need to supply one more argument.

Should update the command to tell the user that it was not enough arguments supplied
